
addons:
  apt:
    packages:
    - aria2
#before_install:
branches:
  only:
  - develop
  - master

dist: trusty
env:
  global:
  - IMAGE_ARG_JAVA10_VERSION_BUILD=11
  - IMAGE_TAG_LATEST=10.0.1
  matrix:
  - IMAGE_ARG_JAVA10_VERSION=10.0.1 IMAGE_ARG_JAVA10_PACKAGE_DIGEST=fb4372174a714e6b8c52526dc134031e

group: edge
#install: true

#before_script:
script:
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash build.sh
- kill %1
#after_script:

services:
- docker
sudo: required
