
addons:
  apt:
    packages:
    - aria2
#before_install:
branches:
  only:
  - develop
  - master

dist: trusty
env:
  global:
  - IMAGE_TAG_LATEST=10.0.2
  matrix:
  #- IMAGE_ARG_JAVA10_VERSION=10.0.1 IMAGE_ARG_JAVA10_VERSION_BUILD=10 IMAGE_ARG_JAVA10_PACKAGE_DIGEST=fb4372174a714e6b8c52526dc134031e
  - IMAGE_ARG_JAVA10_VERSION=10.0.2 IMAGE_ARG_JAVA10_VERSION_BUILD=13 IMAGE_ARG_JAVA10_PACKAGE_DIGEST=19aef61b38124481863b1413dce1855f


group: edge
#install: true

#before_script:
script:
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash build.sh
- kill %1
#after_script:

services:
- docker
sudo: required
